### ISSUE TITLE
what is the license of this repository?

### ISSUE THREAD

**Issue by ghost** [heavymetal-ns/heavymetal-ns.github.io#1]
Hi.

I would like to know what is the license of this repository. What is the license of this repository? Is MIT? GPL? Unlicensed? (I would like to use the repository for something I'm doing, creating)

**Comment by natanfelles** [comment]
Hello @villenmarx !

You can use the template. But ensure that you remove all chapters and images from the original.

Put a link in the footer quoting that the template was created by **Natan Felles** in a link to [https://natanfelles.github.io](https://natanfelles.github.io).

If possible, send me the link of the site where you will use the template.

Good job!

**Comment by ghost** [comment]
Hey natanfelles.

> You can use the template. But ensure that you remove all chapters and images from the original.

thanks! So I am happy with this comment here.

> If possible, send me the link of the site where you will use the template.

I will send it out this week. **Update: See this: `https://randommachine.github.io/poems/`**

> Good job!

thanks!
