### ISSUE TITLE
criar versão do heavymetal-ns em audiobook?

### ISSUE THREAD

**Issue by ghost** [heavymetal-ns/heavymetal-ns.github.io#2]

**Comment by natanfelles** [comment]
Olá, @lucasnuic !
Fico muito feliz com seu interesse em ajudar!
Poderia me dizer como pretende criar os áudios? Existem falas dos personagens além da narração...

**Comment by natanfelles** [comment]
Boa ideia. Achei esse site bem interessante: https://www.naturalreaders.com/online/

Se você achar outro tudo bem.

Já pode começar, se quiser.

**Comment by natanfelles** [comment]
Crie uma pastas para os áudios com o número dos capítulos.

Adicione uma tag de áudio nos arquivos HTML, bem no começo, com os arquivos correspondentes.

Faz um de cada vez para enviar as PRs, que daí vou analisar um por um.

**Comment by natanfelles** [comment]
@lucasnuic você poderia upar cada áudio para algum site ou enviar para meu e-mail?

Peço para fazer isso porque se precisar fazer alguma alteração na Pull Request não precisará modificar o áudio, que é um arquivo muito pesado.

Depois de analisar o áudio você abre a PR. Pode ser?

**Comment by natanfelles** [comment]
... Faz e envia um de cada vez, por favor.

**Comment by natanfelles** [comment]
> por que não enviar o link direto do arquivo de áudio em vez de armazenar localmente?

Pretendo colocar os audios separados por capítulos, depois dos títulos. Acha que deveria ter uma versão completa para quem quiser baixar?

> vou enviar o link do audiobook num servidor temporário caso queira escutá-los. pode ser?

Sim. Qual o link?

> fiz alguns áudios com o climpchamp lá tem vários tipos de vozes, estou selecionando algumas que são mais humanizadas do que robotizadas.

Perfeito! :smile:

**Comment by natanfelles** [comment]
Bah. Expirou.
Poderia compatilhar no Google Drive?

**Comment by natanfelles** [comment]
Gostei. Mas parece que a voz vai falhando. Será que é possível corrigir isso?

**Comment by natanfelles** [comment]
Gostei. Mas prefiro uma voz masculina para a narração.

**Comment by natanfelles** [comment]
Primeiro tenho que ouvir a intro com voz masculina.

O arquivo intro.mp4 possui 1.3 MB. Se enviar isso numa PR e depois ter que atualizar vai ficar muito pesado.

Por favor, manda a intro com voz masculina no file.io para mim analisar, daí te respondo qual usar.

---

Ouça a [voz desse site](https://www.bibliaonline.com.br/nvt/lc/19). Tem um triângulo para dar play no lado do título...

Se tiver essa voz, pode ser ela.

Obrigado.

**Comment by natanfelles** [comment]
Ok. Aguardo você achar a voz.

Por favor, quando achar, coloca o link com o Capitulo 2 aqui.

 Capitulo 2 porque ele tem falas. Quero ouvir como fica.

Valeu!

**Comment by natanfelles** [comment]
Ok. Obrigado @newprogrammers01 !
